/**
 * maps minecraft 1.6 item/block ids to prismarinejs minecraft-assets
 * texture paths (1.16.4 naming, served from CDN)
 *
 * base url: https://raw.githubusercontent.com/PrismarineJS/minecraft-assets/master/data/1.16.4/
 * append `.png` to each path
 */

// item ids 256+
// the prismarinejs CDN uses plural folder names: items/ and blocks/
const ITEM_PATHS: Record<number, string> = {
  256: 'items/iron_shovel',
  257: 'items/iron_pickaxe',
  258: 'items/iron_axe',
  259: 'items/flint_and_steel',
  260: 'items/apple',
  261: 'items/bow',
  262: 'items/arrow',
  263: 'items/coal',
  264: 'items/diamond',
  265: 'items/iron_ingot',
  266: 'items/gold_ingot',
  267: 'items/iron_sword',
  268: 'items/wooden_sword',
  269: 'items/wooden_shovel',
  270: 'items/wooden_pickaxe',
  271: 'items/wooden_axe',
  272: 'items/stone_sword',
  273: 'items/stone_shovel',
  274: 'items/stone_pickaxe',
  275: 'items/stone_axe',
  276: 'items/diamond_sword',
  277: 'items/diamond_shovel',
  278: 'items/diamond_pickaxe',
  279: 'items/diamond_axe',
  280: 'items/stick',
  281: 'items/bowl',
  282: 'items/mushroom_stew',
  283: 'items/golden_sword',
  284: 'items/golden_shovel',
  285: 'items/golden_pickaxe',
  286: 'items/golden_axe',
  287: 'items/string',
  288: 'items/feather',
  289: 'items/gunpowder',
  290: 'items/wooden_hoe',
  291: 'items/stone_hoe',
  292: 'items/iron_hoe',
  293: 'items/diamond_hoe',
  294: 'items/golden_hoe',
  295: 'items/wheat_seeds',
  296: 'items/wheat',
  297: 'items/bread',
  298: 'items/leather_helmet',
  299: 'items/leather_chestplate',
  300: 'items/leather_leggings',
  301: 'items/leather_boots',
  302: 'items/chainmail_helmet',
  303: 'items/chainmail_chestplate',
  304: 'items/chainmail_leggings',
  305: 'items/chainmail_boots',
  306: 'items/iron_helmet',
  307: 'items/iron_chestplate',
  308: 'items/iron_leggings',
  309: 'items/iron_boots',
  310: 'items/diamond_helmet',
  311: 'items/diamond_chestplate',
  312: 'items/diamond_leggings',
  313: 'items/diamond_boots',
  314: 'items/golden_helmet',
  315: 'items/golden_chestplate',
  316: 'items/golden_leggings',
  317: 'items/golden_boots',
  318: 'items/flint',
  319: 'items/porkchop',
  320: 'items/cooked_porkchop',
  321: 'items/painting',
  322: 'items/golden_apple',
  323: 'items/oak_sign',
  324: 'items/oak_door',
  325: 'items/bucket',
  326: 'items/water_bucket',
  327: 'items/lava_bucket',
  328: 'items/minecart',
  329: 'items/saddle',
  330: 'items/iron_door',
  331: 'items/redstone',
  332: 'items/snowball',
  333: 'items/oak_boat',
  334: 'items/leather',
  335: 'items/milk_bucket',
  336: 'items/brick',
  337: 'items/clay_ball',
  338: 'items/sugar_cane',
  339: 'items/paper',
  340: 'items/book',
  341: 'items/slime_ball',
  342: 'items/chest_minecart',
  343: 'items/furnace_minecart',
  344: 'items/egg',
  345: 'items/compass',
  346: 'items/fishing_rod',
  347: 'items/clock',
  348: 'items/glowstone_dust',
  349: 'items/cod',
  350: 'items/cooked_cod',
  351: 'items/ink_sac',
  352: 'items/bone',
  353: 'items/sugar',
  354: 'items/cake',
  355: 'items/white_bed',
  356: 'items/repeater',
  357: 'items/cookie',
  358: 'items/filled_map',
  359: 'items/shears',
  360: 'items/melon_slice',
  361: 'items/pumpkin_seeds',
  362: 'items/melon_seeds',
  363: 'items/beef',
  364: 'items/cooked_beef',
  365: 'items/chicken',
  366: 'items/cooked_chicken',
  367: 'items/rotten_flesh',
  368: 'items/ender_pearl',
  369: 'items/blaze_rod',
  370: 'items/ghast_tear',
  371: 'items/gold_nugget',
  372: 'items/nether_wart',
  373: 'items/potion',
  374: 'items/glass_bottle',
  375: 'items/spider_eye',
  376: 'items/fermented_spider_eye',
  377: 'items/blaze_powder',
  378: 'items/magma_cream',
  379: 'items/brewing_stand',
  380: 'items/cauldron',
  381: 'items/ender_eye',
  382: 'items/glistering_melon_slice',
  384: 'items/experience_bottle',
  385: 'items/fire_charge',
  386: 'items/writable_book',
  387: 'items/written_book',
  388: 'items/emerald',
  389: 'items/item_frame',
  390: 'items/flower_pot',
  391: 'items/carrot',
  392: 'items/potato',
  393: 'items/baked_potato',
  394: 'items/poisonous_potato',
  395: 'items/map',
  396: 'items/golden_carrot',
  397: 'items/skeleton_skull',
  398: 'items/carrot_on_a_stick',
  399: 'items/nether_star',
  400: 'items/pumpkin_pie',
  401: 'items/firework_rocket',
  402: 'items/firework_star',
  403: 'items/enchanted_book',
  404: 'items/comparator',
  405: 'items/netherbrick',
  406: 'items/quartz',
  407: 'items/tnt_minecart',
  408: 'items/hopper_minecart',
  417: 'items/iron_horse_armor',
  418: 'items/golden_horse_armor',
  419: 'items/diamond_horse_armor',
  420: 'items/lead',
  421: 'items/name_tag',
}

// block ids 1–255
const BLOCK_PATHS: Record<number, string> = {
  1:   'blocks/stone',
  2:   'blocks/grass_block_top',
  3:   'blocks/dirt',
  4:   'blocks/cobblestone',
  5:   'blocks/oak_planks',
  6:   'blocks/oak_sapling',
  7:   'blocks/bedrock',
  12:  'blocks/sand',
  13:  'blocks/gravel',
  14:  'blocks/gold_ore',
  15:  'blocks/iron_ore',
  16:  'blocks/coal_ore',
  17:  'blocks/oak_log',
  18:  'blocks/oak_leaves',
  20:  'blocks/glass',
  21:  'blocks/lapis_ore',
  22:  'blocks/lapis_block',
  23:  'blocks/dispenser_front',
  24:  'blocks/sandstone',
  25:  'blocks/note_block',
  27:  'blocks/powered_rail_on',
  28:  'blocks/detector_rail',
  30:  'blocks/cobweb',
  35:  'blocks/white_wool',
  37:  'blocks/dandelion',
  38:  'blocks/poppy',
  39:  'blocks/brown_mushroom',
  40:  'blocks/red_mushroom',
  41:  'blocks/gold_block',
  42:  'blocks/iron_block',
  44:  'blocks/stone_slab_top',
  45:  'blocks/bricks',
  46:  'blocks/tnt_side',
  47:  'blocks/bookshelf',
  48:  'blocks/mossy_cobblestone',
  49:  'blocks/obsidian',
  50:  'blocks/torch',
  52:  'blocks/spawner',
  53:  'blocks/oak_planks',
  54:  'blocks/chest_front',
  56:  'blocks/diamond_ore',
  57:  'blocks/diamond_block',
  58:  'blocks/crafting_table_front',
  61:  'blocks/furnace_front',
  65:  'blocks/ladder',
  66:  'blocks/rail',
  67:  'blocks/cobblestone',
  69:  'blocks/lever',
  73:  'blocks/redstone_ore',
  76:  'blocks/redstone_torch',
  78:  'blocks/snow',
  79:  'blocks/ice',
  80:  'blocks/snow',
  81:  'blocks/cactus_side',
  82:  'blocks/clay',
  83:  'blocks/sugar_cane',
  84:  'blocks/jukebox_side',
  85:  'blocks/oak_planks',
  86:  'blocks/pumpkin_side',
  87:  'blocks/netherrack',
  88:  'blocks/soul_sand',
  89:  'blocks/glowstone',
  91:  'blocks/jack_o_lantern',
  92:  'blocks/cake_side',
  96:  'blocks/oak_trapdoor',
  98:  'blocks/stone_bricks',
  101: 'blocks/iron_bars',
  102: 'blocks/glass_pane_top',
  103: 'blocks/melon_side',
  106: 'blocks/vine',
  112: 'blocks/nether_bricks',
  116: 'blocks/enchanting_table_top',
  121: 'blocks/end_stone',
  129: 'blocks/emerald_ore',
  130: 'blocks/ender_chest_front',
  133: 'blocks/emerald_block',
  137: 'blocks/command_block_front',
  138: 'blocks/beacon',
  139: 'blocks/cobblestone',
  145: 'blocks/anvil_top',
  152: 'blocks/redstone_block',
  153: 'blocks/nether_quartz_ore',
  155: 'blocks/quartz_block_side',
  159: 'blocks/white_terracotta',
  170: 'blocks/hay_block_side',
  172: 'blocks/terracotta',
  173: 'blocks/coal_block',
  174: 'blocks/packed_ice',
}

const CDN = 'https://raw.githubusercontent.com/PrismarineJS/minecraft-assets/master/data/1.16.4/'

export function getTexturePath(id: number): string | null {
  if (id >= 256) return ITEM_PATHS[id] ?? null
  return BLOCK_PATHS[id] ?? null
}

export function getTextureUrl(id: number): string | null {
  const path = getTexturePath(id)
  return path ? CDN + path + '.png' : null
}
